Rob-erto/config/routes.rb
Rails.application.routes.draw do

  get 'pro_user_failure/index'
  get 'pro_user_ok/index'
  get 'amici/index'
  get 'profilo/index'
  get 'help/index'
  get 'home/index'
  root 'home#index'

  resource :chat
  post 'create_chat', to: 'home#create_chat', as: 'create_chat'#per creare chat eventualmente quando si fa la logica
  get 'mostra_chat', to: 'home#mostra_chat', as: 'mostra_chat'
  patch 'cambia_nome_chat/:chat_id', to: 'home#cambia_nome_chat', as: 'cambia_nome_chat'
  post 'aggiungi_ai_preferiti/:chat_id', to: 'home#aggiungi_ai_preferiti', as: 'aggiungi_ai_preferiti'
  post 'rimuovi_dai_preferiti/:chat_id', to: 'home#rimuovi_dai_preferiti', as: 'rimuovi_dai_preferiti'
  post '/send_msg', to: 'home#send_msg'     # per invocare send_msg di HomeController dalla view
  post '/invia_domanda/:domanda', to:'home#invia_domanda', as: 'invia_domanda'
  get 'change_theme', to: 'application#change_theme'  # per cambiare il tema

  delete '/home/:id/delete_message', to: 'home#delete_message', as: :delete_message  # per eliminare un messaggio
  delete '/home/:id/delete_chat', to: 'home#delete_chat', as: :delete_chat
  get 'set_aimodel/:ai_model', to: 'home#set_aimodel', as: 'set_aimodel'  # per settare il modello di IA

  patch '/users/update_nickname', to: 'users#update_nickname', as: 'update_nickname' # per aggiornare il nickname

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks', sessions: 'sessions' }
  #change the route from /users/login to /login route
  devise_scope :user do
    get 'login', to: 'sessions#new'
  end
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  patch 'users/:id/update_profile_image', to: 'profilo#update_profile_image' # per aggiornare l'immagine del profilo

  resources :users do
    get 'amici', on: :collection
  end
  resources :amici do
    member do
      put :accept
      delete :destroy
    end
  end

  post '/condividi_chat', to: 'home#condividi_chat' #per condividere la chat
  delete '/rimuovi_chat_condivisa', to: 'home#rimuovi_chat_condivisa'   # per rimuovere la chat condivisa
  resources :shares, only: [:create, :destroy]

end

Rob-erto/app/controllers/amici_controller.rb
class AmiciController < ApplicationController
  before_action :set_amico, only: [:show, :edit, :update, :destroy]

  def index
    @friendships = current_user.friendships.where(status: 1)
    @friendship = Friendship.new
  end

  def show
  end

  def new
    @friendship = Friendship.new
  end

  def create
    @friend = User.find_by(email: params[:friendship][:friend_email])
    if @friend
      existing_friendship = Friendship.find_by(user_id: current_user.id, friend_id: @friend.id)
      if existing_friendship
        redirect_to amici_index_path, alert: 'Esiste già una richiesta di amicizia.'
      else
        @friendship = current_user.friendships.build(friend_id: @friend.id, status: 0)

        if @friendship.save
          redirect_to amici_index_path, notice: 'Richiesta di amicizia inviata.'
        else
          redirect_to amici_index_path, alert: @friendship.errors.full_messages.to_sentence
        end
      end
    else
      redirect_to amici_index_path, alert: 'Utente non trovato.'
    end
  end

  def edit
  end

  def update
    if @friendship.update(friendship_params)
      redirect_to amici_path, notice: 'Friendship was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @mirror_friendship = Friendship.find_by(user_id: @friendship.friend_id, friend_id: @friendship.user_id, status: 1)

    if @friendship.destroy
      @mirror_friendship.destroy if @mirror_friendship
      redirect_to amici_index_path, notice: 'Richiesta di amicizia cancellata.'
    else
      redirect_to amici_index_path, alert: 'Si è verificato un errore nel rifiutare la richiesta di amicizia.'
    end
  end

  def accept
    @friendship = Friendship.find(params[:id])
    if @friendship.update(status: 1)
      Friendship.create(user_id: @friendship.friend_id, friend_id: @friendship.user_id, status: 1)
      redirect_to amici_index_path, notice: 'Richiesta di amicizia accettata.'
    else
      redirect_to amici_index_path, alert: 'Si è verificato un errore nell\'accettare la richiesta di amicizia.'
    end
  end



  private

  def set_amico
    @friendship = Friendship.find(params[:id])
  end

  def friendship_params
    params.require(:friendship).permit(:friend_id, :status)
  end
end

Rob-erto/app/helpers/amici_helper.rb
module AmiciHelper
end

Rob-erto/app/views/amici/index.html.erb
<<div class="container z-index-1">
    <div class="row justify-content-center custom-height">
        <div class="col-12 col-md-10 col-lg-8">
            <div class="p-3 mb-2 bg-dark text-white rounded custom-shadow text-center">
                <h1>Invia una richiesta di amicizia</h1>

                <%= form_with model: @friendship, url: {controller: "amici", action: "create"}, local: true, class: 'row g-3 justify-content-center' do |form| %>
                <% if @friendship.errors.any? %>
                    <div id="error_explanation">
                    <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>
                    <ul>
                        <% @friendship.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                    </ul>
                    </div>
                <% end %>

                <div class="col-auto">
                    <div class="input-group">
                    <%= form.label :friend_email, 'Email Amico', class: 'input-group-text' %>
                    <%= form.text_field :friend_email, class: 'form-control', placeholder: 'Email' %>
                    </div>
                </div>

                <div class="col-auto">
                    <%= form.submit 'Submit', class: 'btn btn-primary mb-3' %>
                </div>
                <% end %>

                <h1>Amici</h1>
                <table class="table table-striped table-dark table-bordered">
                <thead>
                    <tr>
                    <th>Friend ID</th>
                    <th>Azioni</th>
                    </tr>
                </thead>
                <tbody>
                    <% @friendships.each do |friendship| %>
                    <tr>
                        <td><%= friendship.friend.name %></td>
                        <td>
                        <%= button_to 'Rimuovi', amici_path(friendship), method: :delete, data: { confirm: 'Sei sicuro?' }, class: 'btn btn-danger' %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
                </table>

                <h1>Richieste di amicizia pendenti</h1>

                <table class="table table-striped table-dark table-bordered">
                <thead>
                    <tr>
                    <th>Friend ID</th>
                    <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                <% (current_user.friendships.where(status: 0) + Friendship.where(friend_id: current_user.id, status: 0)).each do |friendship| %>
                    <tr>
                    <td><%= friendship.user == current_user ? friendship.friend.name : friendship.user.name %></td>
                    <td>
                        <% if friendship.user == current_user %>
                        <%= button_to 'Annulla', amici_path(friendship), method: :delete, data: { confirm: 'Sei sicuro?' }, class: 'btn btn-danger' %>
                        <% else %>
                        <%= button_to 'Accetta', accept_amici_path(friendship), method: :put, class: 'btn btn-primary mb-3' %>
                        <%= button_to 'Rifiuta', amici_path(friendship), method: :delete, data: { confirm: 'Sei sicuro?' }, class: 'btn btn-danger' %>
                        <% end %>
                    </td>
                    </tr>
                <% end %>
                </tbody>
            </div>
        </div>
    </div>
</div>