Rob-erto/config/routes.rb
Rails.application.routes.draw do

  get 'pro_user_failure/index'
  get 'pro_user_ok/index'
  get 'amici/index'
  get 'profilo/index'
  get 'help/index'
  get 'home/index'
  root 'home#index'

  resource :chat
  post 'create_chat', to: 'home#create_chat', as: 'create_chat'#per creare chat eventualmente quando si fa la logica
  get 'mostra_chat', to: 'home#mostra_chat', as: 'mostra_chat'
  patch 'cambia_nome_chat/:chat_id', to: 'home#cambia_nome_chat', as: 'cambia_nome_chat'
  post 'aggiungi_ai_preferiti/:chat_id', to: 'home#aggiungi_ai_preferiti', as: 'aggiungi_ai_preferiti'
  post 'rimuovi_dai_preferiti/:chat_id', to: 'home#rimuovi_dai_preferiti', as: 'rimuovi_dai_preferiti'
  post '/send_msg', to: 'home#send_msg'     # per invocare send_msg di HomeController dalla view
  post '/invia_domanda/:domanda', to:'home#invia_domanda', as: 'invia_domanda'
  get 'change_theme', to: 'application#change_theme'  # per cambiare il tema

  delete '/home/:id/delete_message', to: 'home#delete_message', as: :delete_message  # per eliminare un messaggio
  delete '/home/:id/delete_chat', to: 'home#delete_chat', as: :delete_chat
  get 'set_aimodel/:ai_model', to: 'home#set_aimodel', as: 'set_aimodel'  # per settare il modello di IA

  patch '/users/update_nickname', to: 'users#update_nickname', as: 'update_nickname' # per aggiornare il nickname

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks', sessions: 'sessions' }
  #change the route from /users/login to /login route
  devise_scope :user do
    get 'login', to: 'sessions#new'
  end
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  patch 'users/:id/update_profile_image', to: 'profilo#update_profile_image' # per aggiornare l'immagine del profilo

  resources :users do
    get 'amici', on: :collection
  end
  resources :amici do
    member do
      put :accept
      delete :destroy
    end
  end

  post '/condividi_chat', to: 'home#condividi_chat' #per condividere la chat
  delete '/rimuovi_chat_condivisa', to: 'home#rimuovi_chat_condivisa'   # per rimuovere la chat condivisa
  resources :shares, only: [:create, :destroy]

end

Rob-erto/app/controllers/profilo_controller.rb
class ProfiloController < ApplicationController
  def index
    session[:pro_user_check] = User.where('users.id = ?', session[:user_id]).first.pro
    @pro_user_check = session[:pro_user_check]
  end


  def update_profile_image
    @user = current_user
    if @user.update(profile_image: params[:image])
      render json: { message: 'Immagine profilo caricata' }
    else
      render json: { error: 'Errore durante il caricamento dell\'immagine del profilo' }, status: :unprocessable_entity
    end
  end
end

Rob-erto/app/helpers/profilo_helper.rb
module ProfiloHelper
end

Rob-erto/app/views/profilo/index.html.erb
<head>
    <%= csrf_meta_tags %>
</head>
<body>
    <div class="container z-index-1">
        <div class="row justify-content-center custom-height">
            <div class="col-12 col-md-8 col-lg-6">
            <div class="p-3 mb-2 bg-dark text-white rounded custom-shadow text-center">
                <p>Benvenuto nella tua sezione Profilo!</p>
                <% unless user_signed_in? %>
                <p>Non hai ancora effettuato il login oppure sei un nuovo utente?</p>
                <%= button_to "Login", new_user_session_path, method: :get, class: "btn btn-primary mb-2" %>
                <%= button_to "Registrati", new_user_registration_path, method: :get, class: "btn btn-primary mb-2" %>

                <p>Oppure fai il login con Github!</p>
                <%- if devise_mapping.omniauthable? %>
                    <%- resource_class.omniauth_providers.each do |provider| %>
                    <%= button_to "Entra con #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false }, class: "btn btn-primary mb-2" %>
                    <% end %>
                <% end %>
                <% else %>
                <meta name="csrf-token" content="<%= form_authenticity_token %>">
                <div class="popup" id="img-window">
                    <h2>Seleziona il tuo avatar!</h2>
                    <div id="immaginiProfilo">
                    </div>
                    <button class="button_1 btn btn-danger" onclick="closePopup()">INDIETRO</button>
                </div>
                <div class="user-informations">
                    <img src="<%= asset_path("account/img#{current_user.profile_image}.png") %>" alt="avatar" id="avatar" class="avatar">
                    <% if current_user.pro %>
                        <p class="username" id="procheck" data-username="<%= current_user.nickname %>"><%= current_user.nickname %></p>
                    <%else%>
                        <p class="username" id="noprocheck" data-username="<%= current_user.nickname %>"><%= current_user.nickname %></p>
                    <%end%>
                </div>
                <div class="border-top">
                    <p>Informazioni Generali:</p>
                    <p>Email: <%= current_user.email %></p>
                    <p>Username: <%= current_user.name %></p>
                </div> 
                <div class="border-top">
                    <p>Personalizza il tuo profilo!</p>
                    <button class="btn btn-primary" onclick="openPopup()">Cambia avatar!</button>
                </div>
                <br>
                <% if @pro_user_check %>
                    <p>Non ti piace il nickname?</p>
                    <div class="d-flex justify-content-center align-items-center">
                        <%= form_with(model: current_user, url: update_nickname_path, method: :patch, local: true, html: { class: 'row g-3' }) do |form| %>
                        <div class="col-auto">
                            <%= form.label :nickname, class: 'visually-hidden' %>
                            <%= form.text_field :nickname, class: 'form-control', placeholder: 'Nickname' %>
                        </div>
                        <div class="col-auto">
                            <%= form.submit "Cambia nickname", class: "btn btn-primary mb-3" %>
                        </div>
                        <% end %>
                    </div>
                <% end %>
                <div class="border-top">
                    <p>Vuoi cambiare profilo?</p>
                    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
                </div>
                

                <div class="border-top mt-2 text-center">
                    <p>Non sei soddisfatto? Puoi cancellare l'account se vuoi ma poi non sarai mai più uno di noi.</p>
                    <%= button_to 'Elimina account', user_registration_path, method: :delete, class: "btn btn-danger",data: { confirm: 'Sei sicuro di voler eliminare il tuo account?' } %>
                </div>
                <% if !current_user.pro %>
                    <div class="border-top mt-2 text-center">
                        <p class="py-1">Diventa un utente pro e potrai utilizzare più funzionalità di Rob-erto come: </p>  
                        <ul class="d-inline-block text-left">
                            <li>Scegliere il modello di intelligenza artificiale</li>
                            <li>Cambiare il colore del chatbox e del font e altro!</li>
                        </ul>
                            <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
                                <input type="image" src="https://www.paypalobjects.com/it_IT/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Buy Now" />
                                <img alt="" border="0" src="https://www.sandbox.paypal.com/it_IT/i/scr/pixel.gif" width="1" height="1" />
                                <input type="hidden" name="no_shipping" value="2" />
                                <input type="hidden" name="amount" value="1.00" />
                                <input type="hidden" name="business" value="DUNA8WP58E6NN" />
                                <input type="hidden" name="no_note" value="0" />
                                <input type="hidden" name="item_name" value="roberto rob" />
                                <input type="hidden" name="button_subtype" value="products" />
                                <input type="hidden" name="cmd" value="_xclick" />
                                <input type="hidden" name="bn" value="DUNA8WP58E6NN:PP-BuyNowBF_P" />
                                <input type="hidden" name="currency_code" value="EUR" />
                                <input type="hidden" name="return" value="http://localhost:3000/pro_user_ok/index">
                                <input type="hidden" name="cancel_return" value="http://localhost:3000/pro_user_failure/index">
                                </form>
                    </div>
                <%else%>
                    <div class="border-top mt-2 text-center">Sei già utente pro</div>
                <%end%>
                <% end %>
            </div>
            </div>
        </div>
    </div>
    <script>
        var assetPaths = <%= (1..38).map { |i| asset_path("account/img#{i}.png") }.to_json.html_safe %>;
    </script>
    <%= javascript_include_tag 'account' %>
</body>