Rob-erto/config/routes.rb
Rails.application.routes.draw do

  get 'pro_user_failure/index'
  get 'pro_user_ok/index'
  get 'amici/index'
  get 'profilo/index'
  get 'help/index'
  get 'home/index'
  root 'home#index'

  resource :chat
  post 'create_chat', to: 'home#create_chat', as: 'create_chat'#per creare chat eventualmente quando si fa la logica
  get 'mostra_chat', to: 'home#mostra_chat', as: 'mostra_chat'
  patch 'cambia_nome_chat/:chat_id', to: 'home#cambia_nome_chat', as: 'cambia_nome_chat'
  post 'aggiungi_ai_preferiti/:chat_id', to: 'home#aggiungi_ai_preferiti', as: 'aggiungi_ai_preferiti'
  post 'rimuovi_dai_preferiti/:chat_id', to: 'home#rimuovi_dai_preferiti', as: 'rimuovi_dai_preferiti'
  post '/send_msg', to: 'home#send_msg'     # per invocare send_msg di HomeController dalla view
  post '/invia_domanda/:domanda', to:'home#invia_domanda', as: 'invia_domanda'
  get 'change_theme', to: 'application#change_theme'  # per cambiare il tema

  delete '/home/:id/delete_message', to: 'home#delete_message', as: :delete_message  # per eliminare un messaggio
  delete '/home/:id/delete_chat', to: 'home#delete_chat', as: :delete_chat
  get 'set_aimodel/:ai_model', to: 'home#set_aimodel', as: 'set_aimodel'  # per settare il modello di IA

  patch '/users/update_nickname', to: 'users#update_nickname', as: 'update_nickname' # per aggiornare il nickname

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks', sessions: 'sessions' }
  #change the route from /users/login to /login route
  devise_scope :user do
    get 'login', to: 'sessions#new'
  end
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  patch 'users/:id/update_profile_image', to: 'profilo#update_profile_image' # per aggiornare l'immagine del profilo

  resources :users do
    get 'amici', on: :collection
  end
  resources :amici do
    member do
      put :accept
      delete :destroy
    end
  end

  post '/condividi_chat', to: 'home#condividi_chat' #per condividere la chat
  delete '/rimuovi_chat_condivisa', to: 'home#rimuovi_chat_condivisa'   # per rimuovere la chat condivisa
  resources :shares, only: [:create, :destroy]

end

Rob-erto/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if session[:first_visit].nil? || session[:first_visit] == true   # primo accesso alla pagina
      reset_session
      session[:first_visit] = false

      # Elimina tutti i base_user che non hanno aggiornato alcuna chat da più di 3 ore
      #User.joins(:chat).where(name: 'base_user').where('chats.updated_at < ?', 3.hours.ago).destroy_all
      User.where('users.name = ?', 'base_user').destroy_all
      # vengono eliminate di conseguenza tutte le chat associate agli utenti eliminati e tutti i messaggi associati alle chat eliminate

      # ------------------ Crea un nuovo base_user
      nuovo_base_user = User.new
      nuovo_base_user.name = 'base_user'
      nuovo_base_user.email = 'base_user@fake_email'
      nuovo_base_user.password = 'base_user_password'
      nuovo_base_user.save        # Salva l'utente nel database
      # ------------------ Crea nuova chat per il base-user
      nuovaChat = Chat.new
      nuovaChat.user_id = nuovo_base_user.id
      nuovaChat.nome = 'Chatta con AI'
      nuovaChat.save       # Salva la chat nel database

      session[:user_id] = nuovo_base_user.id
      session[:chat_id] = nuovaChat.id
      session[:chat_name] = nuovaChat.nome

      session[:messages] = []
      session[:ai_model] = 'mixtral-8x7b-32768'



    end


    session[:user_name] = User.where('users.id = ?', session[:user_id]).first.nickname
    session[:pro_user_check] = User.where('users.id = ?', session[:user_id]).first.pro


    if session[:user_name] != 'base_user'  # utente loggato

      if session[:primo_accesso_login] == 0   # primo accesso da utente loggato
        session[:primo_accesso_login] = 1
        session[:chat_not_present] = true

      end

      @list_visibility = true    # visibilità della lista chat
      @friendships = Friendship.where(user_id: session[:user_id], status: 1)
      # @friendships = current_user.friendships.where(status: 1)
      @shared_chats = Chat.joins(:shares).where(shares: { destinatario_id: session[:user_id] })

    else
      session[:primo_accesso_login] = 0
      @list_visibility = false
      session[:chat_not_present] = false

    end


    # ---------------- variabili da mostrare nella pagina ----------------
    # mostra la chat nella chat-area
    @chat_not_present = session[:chat_not_present]
    # messaggi da mostrare nella pagina
    @messages = Message.where('chat_id = ?', session[:chat_id]).order(created_at: :asc)
    # nome della chat corrente
    @chat_name = session[:chat_name]
    # nome dell'user corrente
    @user_name = session[:user_name]
    # ruolo user corrente
    @pro_user_check = session[:pro_user_check]
    # modello di IA
    @ai_model = session[:ai_model]
    # lista delle chat dell'utente loggato
    @chats = Chat.where('chats.user_id = ? ', session[:user_id]).order(preferita: :desc)
    # possibilità di scrivere nella chat
    @not_able_to_write = session[:not_able_to_write]
    # ---------------- variabili da mostrare nella pagina ----------------
  end




  # ------------------------------------------------------------------ invio e ricezione messaggi
  def send_msg

    #session[:response] = "response vuota"
    if params[:user_input].present? or params[:reload].present?

      if params[:user_input].empty? and !params[:reload].present?
        # non fa nulla
        #session[:usr_input] = "user input vuoto"
        #session[:response] = "nada"

      else
        session[:usr_input] = params[:user_input]
        # ---------------- invia messaggio all'AI ----------------

        uri = URI.parse("https://api.groq.com/openai/v1/chat/completions")

        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true

        request = Net::HTTP::Post.new(uri.request_uri)

        request["Content-Type"] = "application/json"
        request["Authorization"] = ENV['API_KEY']


        messaggio = params[:user_input]     # messaggio da inviare

        # gestione traduzioni
        if params[:translate].present? and params[:translate] != "false"
          messaggio = "Translate the following text in " + params[:translate] + ": " + messaggio
        end

        # gestione reload ultimo messaggio
        if params[:reload].present? and params[:reload] != "false"
          if session[:messages].length > 1
            last_message = session[:messages][-1]
            # invia nuovamente il messaggio
            messaggio = last_message["content"]
            session[:usr_input] = messaggio
            # elimina gli ultimi 2 messaggi
            Message.where(chat_id: session[:chat_id]).order(created_at: :desc).limit(2).destroy_all
          else
            # reindirizzamento (aggiorna la pagina)
            redirect_to action: :index and return
          end
        end

        session[:messages].push({"role": "user", "content": messaggio})

        request.body = {
          "model": session[:ai_model],
          "messages": session[:messages]
        }.to_json


        retries = 2   # numero di tentativi di invio del messaggio
        begin
          response = http.request(request)
        rescue Net::ReadTimeout
          retry if (retries -= 1) > 0   # riprova ancora una volta in caso di errore di timeout nella richiesta http
          redirect_to action: :index and return
        end

        response_obj = JSON.parse(response.body)

        if response_obj["choices"]
          response_obj["choices"].each do |choice|
            session[:response] = choice["message"]["content"]
          end
        else
          session[:response] = "Sto avendo dei problemi in questo momento. Prova a inviare nuovamente il messaggio."
        end

        if params[:translate].present? and params[:translate] != "false"
          session[:messages].pop
        end
        # ---------------- invia messaggio all'AI ----------------


        # ---------------- salva i due nuovi messaggi come istanze di Message ----------------
        # user_message
        user_message = Message.new
        user_message.content = session[:usr_input] # messaggio dell'utente
        user_message.message_type = 0     # messaggio utente avrà: message_type = 0
        user_message.chat_id = session[:chat_id]    # associa il messaggio alla chat corrente
        user_message.save

        # ai_message
        ai_message = Message.new
        ai_message.content = session[:response] # messaggio dell'AI
        ai_message.message_type = 1     # messaggio dalll'AI avrà: message_type = 1
        ai_message.chat_id = session[:chat_id]    # associa il messaggio alla chat corrente
        ai_message.save

        # Aggiorna il timestamp updated_at della chat
        chat = Chat.find(session[:chat_id])
        chat.touch
        # ---------------- salva i due nuovi messaggi come istanze di Message ----------------

      end

    else
      # non fa nulla
      session[:usr_input] = "non riesco a leggere user input"
    end

    # reindirizzamento (aggiorna la pagina)
    redirect_to action: :index and return

  end



  # ------------------------------------------------------------------ eliminare messaggi
  def delete_message
    @message = Message.find(params[:id])
    @next_message = Message.where("id > ?", params[:id]).first

    @message.destroy
    @next_message.destroy if @next_message

    # reindirizzamento (aggiorna la pagina)
    redirect_to action: :index
  end


  # ------------------------------------------------------------------ creazione chat
  def new
    @chat = Chat.new
  end

  def create_chat
    chat = Chat.create(user_id: session[:user_id], nome: "Nuova chat")
    chat_id = chat.id
    redirect_to action: :mostra_chat, chat_id: chat_id
  end

  # ------------------------------------------------------------------ mostrare chat
  def mostra_chat
    session[:chat_name] = Chat.where('id = ?', params[:chat_id]).first.nome
    session[:chat_id] = params[:chat_id]
    session[:chat_not_present] = false     # mostra la chat nel chatflow_container

    if params[:condivisa].present? and params[:condivisa] == "true"
      session[:not_able_to_write] = true
    else
      session[:not_able_to_write] = false
    end

    redirect_to action: :index
  end

  # ------------------------------------------------------------------ eliminare chat
  def delete_chat
    @chat = Chat.find(params[:id])
    chat_id = @chat.id
    chat_nome = @chat.nome
    @chat.destroy
    if session[:chat_id] == chat_id || session[:chat_name] == chat_nome     #verifica se hai cancellato la chat che stavi visualizzando
      session[:chat_name] = "Chat cancellata!"
      session[:chat_not_present] = true
    end
    redirect_to action: :index

  end

  # ------------------------------------------------------------------ rinominare chat
  def cambia_nome_chat
    @chat = Chat.where('id = ?', params[:chat_id])
    @chat.update(nome: params[:nome_chat])
    if session[:chat_id].to_s == params[:chat_id]
      session[:chat_name] = params[:nome_chat]
    end
    redirect_to action: :index
  end

  # ------------------------------------------------------------------ inviare domanda suggerita
  def invia_domanda
    # crea la chat
    chat = Chat.create(user_id: session[:user_id], nome: "Nuova chat")
    # mostra la chat
    session[:chat_name] = chat.nome
    session[:chat_id] = chat.id
    session[:chat_not_present] = false     # mostra la chat nel chatflow_container
    # invia la domanda
    params[:user_input] = params[:domanda]
    send_msg
  end

  def aggiungi_ai_preferiti
    @chat = Chat.where('id = ?', params[:chat_id])
    @chat.update(preferita: 1)
    redirect_to action: :index
  end

  def rimuovi_dai_preferiti
    @chat = Chat.where('id = ?', params[:chat_id])
    @chat.update(preferita: 0)
    redirect_to action: :index
  end
  # ------------------------------------------------------------------ cambiare modello di ia
  def set_aimodel

    if params[:ai_model].present?
      if params[:ai_model] == "gemma"

Rob-erto/app/helpers/home_helper.rb
module HomeHelper
end

Rob-erto/app/views/home/index.html.erb
 
<% if @list_visibility %>
<div class="contenitore">
    <div class="title">
        <%= button_to 'Crea chat', create_chat_path(), class: 'crea', id: 'crea_chat_button' %> 
    </div>
    <div class="list"> 
            <div class="list_elems">
            <% if !@chats.empty? %> 
                <% @chats.each do |chat| %>
                <ul class="ul">
                    <li><div class="list_elem_container"><p class="wrapper"><%= link_to chat.nome, mostra_chat_path(chat_id: chat.id), id: 'mostra_chat_link', class:"chat-link", title: chat.nome %></p>
                    <% if chat.preferita==1%>
                        <%= image_tag('star.png',  class: "star-img")%>         
                    <%end%>
                    <button type="button" class="reload-button dropwdown-toggle" data-bs-toggle="dropdown">
                        <%= image_tag('chatmenu.png', alt: "", class: "button-img dropdown-img") %>
                    </button>
                    <ul class="dropdown-menu">
                        <li><input type="submit" value="Cambia nome chat" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#modal-<%= chat.id %>"/></li>
                        <% if chat.preferita==0 %> 
                            <li><%= button_to "Aggiungi chat ai preferiti", aggiungi_ai_preferiti_path(chat_id: chat.id), method: :post, class:"dropdown-item" %></li>
                        <%else%> 
                                <li><%= button_to "Rimuovi chat dai preferiti", rimuovi_dai_preferiti_path(chat_id: chat.id), method: :post, class:"dropdown-item" %></li>
                        <%end%>
                        <li><input type="submit" value="Condividi chat" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#modal-<%= chat.id %>-shared"/></li>
                        <li><%= button_to "Cancella chat", delete_chat_path(chat.id), method: :delete, class: "dropdown-item" %></li>
                    </ul>
                    </div>
                    </li>
                </ul>
                 <!-- POPUP CAMBIA NOME CHAT-->
                        <div class="modal fade" id="modal-<%= chat.id %>" tabindex="-1" role="dialog" aria-labelledby="testmodalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content bg-dark">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="testmodalLabel">Rinomina una chat</h5>
                                    </div>
                                    <div class="modal-body">
                                        <%= form_tag cambia_nome_chat_path(chat), method: :patch, :class => "form-horizontal" do %>
                                                <%= label_tag 'reason', "Inserisci il nuovo nome della chat", :class => 'control-label' %>
                                                <%= text_field_tag :nome_chat, params[:nome_chat], :class => "form-control" %>
                                    </div>
                                    <div class="modal-footer">
                                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancella</button>
                                            <%= submit_tag "Conferma", name: nil, class: "btn btn-success" %>

                                        <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <!-- -->
                    <!-- POPUP CONDIVIDI CHAT-->
                        <div class="modal fade" id="modal-<%= chat.id %>-shared" tabindex="-1" role="dialog" aria-labelledby="testmodalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content bg-dark">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="testmodalLabelShared">Condividi la Chat con</h5>
                                    </div>
                                    <div class="modal-body">
                                        <h1>Amici</h1>
                                        <table class="table table-striped table-dark table-bordered">
                                        <thead>
                                            <tr>
                                            <th>Friend</th>
                                            <th>Azioni</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <% @friendships.each do |friendship| %>
                                            <tr>
                                                <td><%= friendship.friend.nickname %></td>
                                                <td>
                                                <%= button_to 'Condividi', condividi_chat_path, method: :post, params: { mittente: current_user.id, destinatario: friendship.friend_id, chat_id: chat.id }, data: { confirm: 'Sei sicuro?' }, class: 'btn btn-primary' %>
                                                </td>
                                            </tr>
                                            <% end %>
                                        </tbody>
                                        </table>
                                    </div>
                                    <div class="modal-footer">
                                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancella</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <!-- -->
                <% end %>
            <%else%>
               <div class="d inline text-wrap text-center">Non hai nessuna chat creata!</div>
            <%end%>
            </div>
    </div>             
</div> 
<%end%>

<% if @list_visibility %>
<div class="contenitore_shared">
    <div class="title">
        <p class="title_shared">Chat condivise</p>
    </div>
    <div class="list"> 
        <div class="list_elems">
            <% if !@shared_chats.empty? %> 
                <% @shared_chats.each do |chat| %>
                <ul class="ul">
                    <li>
                        <div class="list_elem_container">
                            <p class="wrapper">
                                <%= link_to chat.nome, mostra_chat_path(chat_id: chat.id, condivisa: true), id: 'mostra_chat_link', class:"chat-link", title: chat.nome %>
                            </p>

                            <button type="button" class="reload-button dropwdown-toggle" data-bs-toggle="dropdown">
                                <%= image_tag('chatmenu.png', alt: "", class: "button-img dropdown-img") %>
                            </button>
                            <ul class="dropdown-menu">
                                <%= button_to "Cancella chat condivisa", 
                                rimuovi_chat_condivisa_path(chat_id: chat.id), 
                                method: :delete, 
                                class: "dropdown-item" %>
                            </ul>
                        </div>
                    </li>
                </ul>
                <% end %>
            <% else %>
                <div class="d inline text-wrap text-center">Non hai nessuna chat condivisa!</div>
            <% end %>
        </div>
    </div>    
</div> 
<%end%>

<div class="chat-area">
    <div class="chat-header">
        <div id="nome-user"><%= @user_name %></div>
        <b id="nome-chat"><%= @chat_name %></b>
        <div id="nome-modello"><%= @ai_model %></div>
    </div>

    <% if @chat_not_present %>
        <div class="chatflow_container">
            <!-- domande consigliate da porre alla IA -->
            <h3 class="testo">Ecco alcuni esempi di domande che puoi pormi:</h3> 
            <div id="table">
                <div id="row">
                    <div id="inner"><%= button_to 'Quando è stato costruito il colosseo?', invia_domanda_path('Quando è stato costruito il colosseo?'), class: "button domanda-button"%></div>
                    <div id="inner"><%= button_to 'Chi ha dipinto la Gioconda?', invia_domanda_path('Chi ha dipinto la Gioconda?'), class: "button domanda-button"%></div>
                    <div id="inner"><%= button_to 'Consigliami 3 posti dove andare a mangiare a Roma', invia_domanda_path('Consigliami 3 posti dove andare a mangiare a Roma'), class: "button domanda-button"%></div>
                </div>
            </div>
            
        </div>
    <% else %>
    <div class="chatflow_container">

        <ul class="chatflow">
            
            <li class="chatbox incoming">
                <p>Hi there 👋, how can I help you? <br> Ask me anything ...</p>
            </li>

            <% @messages.each_with_index do |message, index| %>
                <% if message.message_type == 0 %>
                    <li class="chatbox outgoing">
                        <% if !@not_able_to_write %>
                            <%= button_to '', delete_message_path(message), method: :delete, class: 'btn-close' %>
                            <% if index == @messages.rindex { |m| m.message_type == 0 } %>
                                <button type="button" class="reload-button" id="reload_button">
                                    <%= image_tag('reload.svg', alt: "") %>
                                </button>
                            <% end %>
                        <% end %>
                        <p class="chat-message"><%= message.content %></p>
                    </li>
                <% else %>
                    <li class="chatbox incoming">
                        <p class="chat-message"><%= message.content %></p>
                    </li>
                <% end %>
            <% end %>

        </ul>
    </div>
    <%end%>

</div>



<% if !@chat_not_present && !@not_able_to_write %>
<div class="user-area">
        <div class="user-input-container">
            <%= form_tag('/send_msg', method: :post, id: "user_input_form") do %>
                <%= text_area_tag :user_input, "", id: "user_input" %>
                <%= hidden_field_tag :translate, 'false', id: 'translate_input' %>
                <%= hidden_field_tag :reload, 'false', id: 'reload_input' %>
            <% end %>
        </div>
        
        <div class="commands-grid">

            <button type="button" class="button input-button" id="send_button">
                <%= image_tag('send.png', alt: "", class: "button-img") %>
            </button>

            
            <button type="button" class="button input-button dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" id="translate_button">
                <%= image_tag('globe.png', alt: "", class: "button-img") %>
            </button>
            <ul class="dropdown-menu">
                <li><button class="dropdown-item" id="translate-ita">Italiano 🇮🇹</button></li>
                <li><button class="dropdown-item" id="translate-sp">Spagnolo 🇪🇦</button></li>
                <li><button class="dropdown-item" id="translate-fr">Francese 🇫🇷</button></li>
                <li><button class="dropdown-item" id="translate-de">Tedesco 🇩🇪</button></li>
            </ul>


            <% if @pro_user_check %>
                <button type="button" class="button input-button dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" id="aimodel_button">
                    <%= image_tag('model-ai.png', alt: "", class: "button-img") %>
                </button>
                <ul class="dropdown-menu">
                    <li><%= link_to 'Mixtral 8x7b (Mistral)', set_aimodel_path('mixtral'), class: 'dropdown-item' %></li>
                    <li><%= link_to 'Gemma 7b (Google)', set_aimodel_path('gemma'), class: 'dropdown-item' %></li>
                    <li><%= link_to 'LLaMA3 70b (Meta)', set_aimodel_path('llama3-70b'), class: 'dropdown-item' %></li>
                    <li><%= link_to 'LLaMA3 8b (Meta)', set_aimodel_path('llama3-8b'), class: 'dropdown-item' %></li>
                </ul>
            <% end %>


        </div>


</div>
<%end%>

<%= javascript_include_tag "home.js" %>