Rob-erto/config/routes.rb
Rails.application.routes.draw do

  get 'pro_user_failure/index'
  get 'pro_user_ok/index'
  get 'amici/index'
  get 'profilo/index'
  get 'help/index'
  get 'home/index'
  root 'home#index'

  resource :chat
  post 'create_chat', to: 'home#create_chat', as: 'create_chat'#per creare chat eventualmente quando si fa la logica
  get 'mostra_chat', to: 'home#mostra_chat', as: 'mostra_chat'
  patch 'cambia_nome_chat/:chat_id', to: 'home#cambia_nome_chat', as: 'cambia_nome_chat'
  post 'aggiungi_ai_preferiti/:chat_id', to: 'home#aggiungi_ai_preferiti', as: 'aggiungi_ai_preferiti'
  post 'rimuovi_dai_preferiti/:chat_id', to: 'home#rimuovi_dai_preferiti', as: 'rimuovi_dai_preferiti'
  post '/send_msg', to: 'home#send_msg'     # per invocare send_msg di HomeController dalla view
  post '/invia_domanda/:domanda', to:'home#invia_domanda', as: 'invia_domanda'
  get 'change_theme', to: 'application#change_theme'  # per cambiare il tema

  delete '/home/:id/delete_message', to: 'home#delete_message', as: :delete_message  # per eliminare un messaggio
  delete '/home/:id/delete_chat', to: 'home#delete_chat', as: :delete_chat
  get 'set_aimodel/:ai_model', to: 'home#set_aimodel', as: 'set_aimodel'  # per settare il modello di IA

  patch '/users/update_nickname', to: 'users#update_nickname', as: 'update_nickname' # per aggiornare il nickname

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks', sessions: 'sessions' }
  #change the route from /users/login to /login route
  devise_scope :user do
    get 'login', to: 'sessions#new'
  end
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  patch 'users/:id/update_profile_image', to: 'profilo#update_profile_image' # per aggiornare l'immagine del profilo

  resources :users do
    get 'amici', on: :collection
  end
  resources :amici do
    member do
      put :accept
      delete :destroy
    end
  end

  post '/condividi_chat', to: 'home#condividi_chat' #per condividere la chat
  delete '/rimuovi_chat_condivisa', to: 'home#rimuovi_chat_condivisa'   # per rimuovere la chat condivisa
  resources :shares, only: [:create, :destroy]

end

Rob-erto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'logo.png' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <title>Rob-erto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= @theme %>">
  <meta name="csrf-token" content="<%= form_authenticity_token %>">
  <div class="blur-background"></div>

    <header>
      <!--  ----------------------------------------Navbar----------------------------------------  -->
      <nav class="navbar navbar-expand-lg bg-body-tertiary" id="NavBar">

        <div class="container-fluid" id="navbar-id">

          <a class="navbar-brand fw-bold text-uppercase" href="#" id="namep">Rob-erto</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>


          <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link"%>
              </li>

              <li class="nav-item">
                <%= link_to "Profilo", profilo_index_path, class: "nav-link"%>
              </li>

              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Amici", amici_index_path, class: "nav-link"%>
                </li>
              <% end %>

              <li class="nav-item">
                <%= link_to "Help", help_index_path, class: "nav-link"%>
              </li>

            </ul>
            

            <div class="settings-container">

              <div class="window-visibility" id="settings-window">
                <ul class="list-group">

                  <div class="list-group-item">
                    <% if @theme == 'dark' %>
                      <%= link_to image_tag('sun.svg', alt: "", id: "sun-img"), change_theme_path(theme: 'light'), class: "btn theme-img" %>
                    <% else %>
                      <%= link_to image_tag('moon.svg', alt: "", id: "moon-img"), change_theme_path(theme: 'dark'), class: "btn theme-img" %>
                    <% end %>
                  </div>

                  <div class="list-group-item btn-group dropstart">
                    <button class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Sfondo Chat</button>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" id="background-color-1"><span class="dot" style="background-color: #fff5ea;"></span></a></li>
                      <li><a class="dropdown-item" id="background-color-2"><span class="dot" style="background-color: green;"></span></a></li>
                      <li><a class="dropdown-item" id="background-color-3"><span class="dot" style="background-color: gray;"></span></a></li>
                      <li><a class="dropdown-item" id="background-color-4"><span class="dot" style="background-color: rgb(20, 20, 20);"></span></a></li>
                    </ul>
                  </div>

                  
                  <% if @pro_user_check %>
                  <div class="list-group-item btn-group dropstart">
                    <button class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Colore Chatbox</button>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" id="chatbox-color-1"><span class="dot" style="background: linear-gradient(90deg, darkslategrey 50%, goldenrod 50%);"></span></a></li>
                      <li><a class="dropdown-item" id="chatbox-color-2"><span class="dot" style="background: linear-gradient(90deg, #000066 50%, #006666 50%);"></span></a></li>
                      <li><a class="dropdown-item" id="chatbox-color-3"><span class="dot" style="background: linear-gradient(90deg, rgb(20, 20, 20) 50%, greenyellow 50%);"></span></a></li>
                    </ul>
                  </div>

                  <div class="list-group-item btn-group dropstart">
                    <button class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Font</button>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" id="font-1" style="font-family: Arial;">Arial</a></li>
                      <li><a class="dropdown-item" id="font-2" style="font-family: Georgia;">Georgia</a></li>
                      <li><a class="dropdown-item" id="font-3" style="font-family: Courier;">Courier New</a></li>
                      <li><a class="dropdown-item" id="font-4" style="font-family: Cursive;">Cursive</a></li>
                      <li><a class="dropdown-item" id="font-5" style="font-family: Brush Script MT;">Brush Script MT</a></li>
                    </ul>
                  </div>

                  <div class="list-group-item btn-group dropstart">
                    <button class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Colore Font</button>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" id="font-color-1"><span class="dot" style="background-color: #fff5ea;"></span></a></li>
                      <li><a class="dropdown-item" id="font-color-2"><span class="dot" style="background-color: darkorange;"></span></a></li>
                      <li><a class="dropdown-item" id="font-color-3"><span class="dot" style="background-color: #0099FF;"></span></a></li>
                    </ul>
                  </div>
                  <% end %>
                  

                </ul>
              </div>

              <button class="btn nav-link" id="settings-img-container">
                <%= image_tag('settings.svg', alt: "", class: "settings-img") %>
              </button>

            </div>

          </div>
          

        </div>
      </nav>
      <!--  ----------------------------------------Navbar----------------------------------------  -->

    </header>


     <!--   things for login/logout alerts
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      -->

    
    <%= yield %>

  <% flash.each do |name, msg| %>
  <div class="flash" data-title="<%= name %>" data-message="<%= msg %>" data-type="<%= name == 'notice' ? 'success' : 'error' %>" style="display: none;"></div>
  <% end %>
  
  <%= javascript_include_tag 'letters' %>
  </body>

</html>